In [30]:
from PIL import Image
import numpy as np

In [39]:
def image_svd(percent, u, sigma, vt):
    svd = np.zeros((u.shape[0],vt.shape[1]))
    n = percent * len(sigma)
    n = int(n)
    for i in range(0, n):
        svd[i, i] = sigma[i]
    img = np.matmul(u, svd)
    img = np.matmul(img, vt)
    img[ img >= 255] = 255
    img[  0 >= img ] = 0
    img = img.astype(np.uint8)
    return img

In [40]:
img = Image.open('1.png', 'r')
a = np.array(img)

In [42]:
u0, sigma0, vt0 = np.linalg.svd(a[:, :, 0])
u1, sigma1, vt1 = np.linalg.svd(a[:, :, 1])
u2, sigma2, vt2 = np.linalg.svd(a[:, :, 2])

for p in np.arange(0.1, 1, 0.1):
    R = image_svd(p, u0, sigma0, vt0)
    G = image_svd(p, u1, sigma1, vt1)
    B = image_svd(p, u2, sigma2, vt2)
    
    I = np.stack((R, G, B), 2)
    #保存图片在img文件夹下
    Image.fromarray(I).save("./svd_imgs/svd_" + str(p * 100) + ".png")

In [25]:
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #4X3

In [26]:
U,sigma,VT = np.linalg.svd(data)

In [27]:
U # 4x4

array([[-0.14087668, -0.82471435,  0.5377697 , -0.1039411 ],
       [-0.34394629, -0.42626394, -0.63955314,  0.539418  ],
       [-0.54701591, -0.02781353, -0.33420281, -0.7670127 ],
       [-0.75008553,  0.37063688,  0.43598625,  0.3315358 ]])

In [28]:
sigma #4x3

array([2.54624074e+01, 1.29066168e+00, 2.31173375e-15])

In [29]:
VT #3x3

array([[-0.50453315, -0.5745157 , -0.64449826],
       [ 0.76077568,  0.05714052, -0.64649464],
       [-0.40824829,  0.81649658, -0.40824829]])